### ISSUE TITLE
Question around versions

### ISSUE THREAD

**Issue by josephDunne** [RJ/relflow#4]
Hi, quick question around the automatic bumping of app versions. I would like to add a flag to reflow to skip updating the app version - instead it will assume the user has already bumped the app versions and should just use the one in the current .app (it could do a sanity check to make sure it has indeed changed). Would this be feasible? Basically I want to keep my app versions as semantic versions

**Comment by RJ** [comment]
Entirely possible to add a flag for that. At the moment relflow generates a new app version at the start and uses it for all changed apps. As along as you do a sanity check, as mentioned, it'd be perfectly safe to leave the app versions alone.

I gave up on semantic versioning for erlang stuff ages ago, for many of the reasons mentioned in the rebar3 docs: http://www.rebar3.org/docs/dependencies
